### PR TITLE
fix _poll_ready for AttributeError: 'NsqdTCPClient' object has no att…

### PR DESCRIPTION
**Pull request by lambdaq**
When `nsqd`  crashes, the following error would appear,  after the `nsqd` recovers, there is still no connection retry.

```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/miniconda2/lib/python2.7/site-packages/gnsq/consumer.py", line 334, in _poll_ready
    self._redistribute_ready_state()
  File "/home/miniconda2/lib/python2.7/site-packages/gnsq/consumer.py", line 356, in _redistribute_ready_state
    conn.ready(count)
  File "/home/miniconda2/lib/python2.7/site-packages/gnsq/nsqd.py", line 445, in ready
    self.send(nsq.ready(count))
  File "/home/miniconda2/lib/python2.7/site-packages/gnsq/nsqd.py", line 231, in send
    return self.stream.send(data)
AttributeError: 'NsqdTCPClient' object has no attribute 'stream'
```

Hopefully this PR could fix this problem

### CODE REVIEW

**Comment by wtolson** [comment]
Looks like there is actually a race condition between connect and redistribute ready state. I recommend changing [this line](https://github.com/wtolson/gnsq/blob/master/gnsq/consumer.py#L365) to `if state in (INIT, BACKOFF):` instead.

**Comment by lambdaq** [comment]
> Looks like there is actually a race condition between connect and redistribute ready state. I recommend changing [this line](https://github.com/wtolson/gnsq/blob/master/gnsq/consumer.py#L365) to `if state in (INIT, BACKOFF):` instead.

Thanks. I updated my PR. Please take a look.

**Comment by lambdaq** [comment]
@wtolson  looks like consumers will fail to boot at start. Because all `INIT` conns will be set to zero thus trigger re-connect again and again. Any ideas?

**Comment by wtolson** [comment]
I've pushed a fix up to master, can you let me know if it works for you?

**Comment by lambdaq** [comment]
Hi @wtolson, thanks for the fix. I can launch gnsq without problem now.

But for a busy consumer, I've seen lots of "throttle complete, resuming normal operation" message, but yet to see any "backing off for X seconds" message. Is this normal?

**Pull request merged**
